FROM juanluisbaptiste/otrs:latest

RUN yum install -y gcc && \
    yum install -y git && \
    yum install -y perl-App-cpanminus
 RUN git clone https://github.com/OTRS/module-tools /opt/module-tools
 RUN cpanm IO::Socket::SSL::Utils && \
     cpanm --installdeps /opt/module-tools/. 

RUN cp /opt/module-tools/etc/config.pl.dist /opt/module-tools/etc/config.pl 
# && \
# sed -i -e 's///' /opt/module-tools/etc/config.pl